/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias for /health, kept for backwards compatibility */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loaded model metadata */
        get: operations["model_info_v1_models_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibrated PD for one loan application */
        post: operations["predict_one_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predict/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibrated PD for up to 1000 loans */
        post: operations["predict_batch_v1_predict_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SHAP waterfall for a single loan */
        post: operations["explain_one_v1_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain/adaptive-shap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Adaptive SHAP surfaces — monthly heatmap, per-decile attribution, ridge surrogate */
        get: operations["adaptive_shap_v1_explain_adaptive_shap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitor/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drift event timeline (ADWIN + KSWIN) */
        get: operations["drift_status_v1_monitor_drift_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitor/drift/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live drift state (current process) */
        get: operations["drift_live_v1_monitor_drift_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitor/champion-vs-challenger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yearly metrics for the ARF challenger replay */
        get: operations["champion_vs_challenger_v1_monitor_champion_vs_challenger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitor/rolling-vs-frozen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LightGBM retrained yearly vs frozen at 2013 */
        get: operations["rolling_vs_frozen_v1_monitor_rolling_vs_frozen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitor/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rolling calibration metrics */
        get: operations["calibration_status_v1_monitor_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitor/recalibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a sliding-window calibrator refit (background) */
        post: operations["trigger_recalibration_v1_monitor_recalibrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdaptiveShapResponse */
        AdaptiveShapResponse: {
            /**
             * Heatmap
             * @description Mean |SHAP| per (month, feature). Background rebased monthly.
             */
            heatmap: components["schemas"]["ShapHeatmapCell"][];
            /**
             * By Decile
             * @description Per-decile SHAP attribution for the latest scoring window.
             */
            by_decile: components["schemas"]["ShapDecileCell"][];
            /**
             * Ridge Surrogate
             * @description Monthly incremental Ridge surrogate coefficients in logit space.
             */
            ridge_surrogate: components["schemas"]["RidgeCoefRow"][];
            /**
             * Top Features
             * @description Top features by overall mean |SHAP|.
             */
            top_features: string[];
            /**
             * Months
             * @description Sorted month buckets present in the heatmap.
             */
            months: string[];
            /**
             * Deciles
             * @description Sorted deciles present in by_decile.
             */
            deciles: number[];
            /**
             * References
             * @description Papers/methods this surface replicates.
             */
            references?: string[];
        };
        /** BatchPredictionRequest */
        BatchPredictionRequest: {
            /** Loans */
            loans: components["schemas"]["LoanFeatures"][];
        };
        /** BatchPredictionResponse */
        BatchPredictionResponse: {
            /** Predictions */
            predictions: components["schemas"]["PredictionResponse"][];
            /** N */
            n: number;
            /** Latency Ms */
            latency_ms: number;
        };
        /** Body_trigger_recalibration_v1_monitor_recalibrate_post */
        Body_trigger_recalibration_v1_monitor_recalibrate_post: {
            /**
             * Trigger
             * @default manual
             */
            trigger: string;
        };
        /** CalibrationMonitorResponse */
        CalibrationMonitorResponse: {
            /** Yearly */
            yearly: components["schemas"]["CalibrationYearly"][];
            /**
             * Summary
             * @description Mean across rolling years for headline metrics.
             */
            summary: {
                [key: string]: number;
            };
            /** Last Refit At */
            last_refit_at: string | null;
        };
        /** CalibrationYearly */
        CalibrationYearly: {
            /** Year */
            year: number;
            /** Auroc Raw */
            auroc_raw: number;
            /** Auroc Static */
            auroc_static: number;
            /** Auroc Sliding */
            auroc_sliding: number;
            /** Brier Raw */
            brier_raw: number;
            /** Brier Static */
            brier_static: number;
            /** Brier Sliding */
            brier_sliding: number;
            /** Slope Static */
            slope_static: number;
            /** Slope Sliding */
            slope_sliding: number;
        };
        /** ChampionChallengerResponse */
        ChampionChallengerResponse: {
            /** Yearly */
            yearly: components["schemas"]["ChampionChallengerYearly"][];
            /**
             * Summary
             * @description Mean AUROC/KS/Brier across years for the ARF challenger replay.
             */
            summary: {
                [key: string]: number;
            };
            /**
             * Note
             * @description Editorial note: ARF underperforms the LightGBM champion on this dataset (~0.54 vs ~0.65 AUROC). Kept as drift detector, not primary model.
             */
            note: string;
            /** Source */
            source: string;
        };
        /** ChampionChallengerYearly */
        ChampionChallengerYearly: {
            /** Year */
            year: number;
            /** N Test */
            n_test: number;
            /** Base Rate Test */
            base_rate_test: number;
            /** Auroc */
            auroc: number;
            /** Ks */
            ks: number;
            /** Brier */
            brier: number;
            /** Calib Slope */
            calib_slope: number;
        };
        /** DriftEvent */
        DriftEvent: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Detector */
            detector: string;
            /** Type */
            type: string;
        };
        /** DriftMonitorResponse */
        DriftMonitorResponse: {
            /** Total Events */
            total_events: number;
            /** By Detector */
            by_detector: {
                [key: string]: number;
            };
            /** By Year */
            by_year: {
                [key: string]: number;
            };
            /**
             * Recent Events
             * @description Last 20 events, newest first.
             */
            recent_events: components["schemas"]["DriftEvent"][];
            /** Last Observation */
            last_observation: string | null;
            /**
             * Source
             * @description Stream replay this state was computed from (e.g. 'arf_drifts_lc.csv').
             */
            source: string;
        };
        /** ExplanationResponse */
        ExplanationResponse: {
            /** Pd Calibrated */
            pd_calibrated: number;
            /** Pd Raw */
            pd_raw: number;
            /**
             * Base Value
             * @description Model's expected log-odds before applying any feature contribution.
             */
            base_value: number;
            /** Contributions */
            contributions: components["schemas"]["FeatureContribution"][];
            /**
             * Top Drivers
             * @description Top 5 by |shap_value|.
             */
            top_drivers: components["schemas"]["FeatureContribution"][];
            /** Model Version */
            model_version: string;
            /**
             * Issue D Used
             * Format: date
             */
            issue_d_used: string;
        };
        /** FeatureContribution */
        FeatureContribution: {
            /** Feature */
            feature: string;
            /** Value */
            value: number | string | null;
            /** Shap Value */
            shap_value: number;
            /**
             * Direction
             * @description 'risk_up' if shap_value > 0, else 'risk_down'.
             */
            direction: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * HomeOwnership
         * @enum {string}
         */
        HomeOwnership: "MORTGAGE" | "RENT" | "OWN" | "OTHER";
        /** LiveDriftEvent */
        LiveDriftEvent: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Detector */
            detector: string;
            /** Type */
            type: string;
            /** Value */
            value?: number | null;
        };
        /** LiveDriftResponse */
        LiveDriftResponse: {
            /** Samples Seen */
            samples_seen: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Score Buffer Size */
            score_buffer_size: number;
            /** Events Total */
            events_total: number;
            /** Events By Detector */
            events_by_detector: {
                [key: string]: number;
            };
            /** Events Recent */
            events_recent: components["schemas"]["LiveDriftEvent"][];
            /**
             * Last Psi
             * @description Last PSI value per monitored numeric feature (PSI > 0.20 fires a drift event).
             */
            last_psi?: {
                [key: string]: number;
            };
        };
        /**
         * LoanFeatures
         * @description Borrower-side features available at loan origination.
         *
         *     Macro context (``fed_funds_rate``, ``us_unemployment``, etc.) is merged
         *     server-side from FRED based on ``issue_d``. Clients should not supply
         *     macro fields — they are derived.
         */
        LoanFeatures: {
            /**
             * Revenue
             * @description Annual income, USD.
             */
            revenue: number;
            /**
             * Dti N
             * @description Debt-to-income ratio. 999 used as sentinel for missing.
             */
            dti_n: number;
            /**
             * Loan Amnt
             * @description Requested loan amount, USD.
             */
            loan_amnt: number;
            /**
             * Fico N
             * @description FICO score at application.
             */
            fico_n: number;
            /**
             * Experience C
             * @description LendingClub experience class indicator.
             */
            experience_c: number;
            /**
             * Emp Length
             * @description Employment length in years (None if not reported).
             */
            emp_length?: number | null;
            purpose: components["schemas"]["Purpose"];
            home_ownership_n: components["schemas"]["HomeOwnership"];
            /**
             * Addr State
             * @description US two-letter state code.
             */
            addr_state: string;
            /**
             * Zip Code
             * @description First 3 digits of ZIP (LendingClub format, e.g. '350xx').
             */
            zip_code: string;
            /**
             * Issue D
             * @description Origination date for macro lookup. Defaults to today.
             */
            issue_d?: string | null;
        };
        /** ModelInfoResponse */
        ModelInfoResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Trained At */
            trained_at: string | null;
            /**
             * Train Period
             * @description Train slice used by the static champion (e.g. '2007-06 → 2014-12').
             */
            train_period: string;
            /** Feature Count */
            feature_count: number;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** References */
            references?: string[];
        };
        /**
         * PredictionResponse
         * @description Calibrated probability of default + transparency metadata.
         */
        PredictionResponse: {
            /**
             * Pd Calibrated
             * @description Sliding-window calibrated default probability.
             */
            pd_calibrated: number;
            /**
             * Pd Raw
             * @description Raw LightGBM probability (pre-calibration).
             */
            pd_raw: number;
            /**
             * Score 0 1000
             * @description Convenience score: round(1000 * (1 - pd_calibrated)).
             */
            score_0_1000: number;
            /**
             * Risk Band
             * @description Bucket: low / medium / high / very_high.
             */
            risk_band: string;
            /** Model Version */
            model_version: string;
            /**
             * Issue D Used
             * Format: date
             */
            issue_d_used: string;
            /**
             * Macro Snapshot
             * @description Macro values merged for this prediction.
             */
            macro_snapshot: {
                [key: string]: number;
            };
        };
        /**
         * Purpose
         * @enum {string}
         */
        Purpose: "debt_consolidation" | "credit_card" | "home_improvement" | "other" | "major_purchase" | "medical" | "small_business" | "car";
        /** RecalibrationTriggerResponse */
        RecalibrationTriggerResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @description 'accepted' | 'rejected' | 'running'
             */
            status: string;
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /** Detail */
            detail?: string | null;
        };
        /** RidgeCoefRow */
        RidgeCoefRow: {
            /** Month */
            month: string;
            /** Coefs */
            coefs: {
                [key: string]: number;
            };
        };
        /** RollingOOTYearly */
        RollingOOTYearly: {
            /** Year */
            year: number;
            /** N Test */
            n_test: number;
            /** Auroc */
            auroc: number;
            /** Ks */
            ks: number;
            /** Brier */
            brier: number;
            /** Calib Slope */
            calib_slope: number;
        };
        /** RollingVsFrozenResponse */
        RollingVsFrozenResponse: {
            /**
             * Rolling
             * @description LightGBM retrained yearly, evaluated on next year.
             */
            rolling: components["schemas"]["RollingOOTYearly"][];
            /**
             * Frozen
             * @description LightGBM frozen at 2013 cut, evaluated on later years.
             */
            frozen: components["schemas"]["RollingOOTYearly"][];
            /**
             * Summary
             * @description Mean uplift of rolling over frozen (AUROC, KS, Brier).
             */
            summary: {
                [key: string]: number;
            };
            /** Source */
            source: {
                [key: string]: string;
            };
        };
        /** ShapDecileCell */
        ShapDecileCell: {
            /**
             * Decile
             * @description Risk decile (0 = lowest predicted PD, 9 = highest).
             */
            decile: number;
            /** Feature */
            feature: string;
            /** Mean Abs Shap */
            mean_abs_shap: number;
        };
        /** ShapHeatmapCell */
        ShapHeatmapCell: {
            /**
             * Month
             * @description YYYY-MM bucket.
             */
            month: string;
            /** Feature */
            feature: string;
            /** Mean Abs Shap */
            mean_abs_shap: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    model_info_v1_models_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoResponse"];
                };
            };
        };
    };
    predict_one_v1_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanFeatures"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_batch_v1_predict_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_one_v1_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanFeatures"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adaptive_shap_v1_explain_adaptive_shap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdaptiveShapResponse"];
                };
            };
        };
    };
    drift_status_v1_monitor_drift_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftMonitorResponse"];
                };
            };
        };
    };
    drift_live_v1_monitor_drift_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveDriftResponse"];
                };
            };
        };
    };
    champion_vs_challenger_v1_monitor_champion_vs_challenger_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionChallengerResponse"];
                };
            };
        };
    };
    rolling_vs_frozen_v1_monitor_rolling_vs_frozen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollingVsFrozenResponse"];
                };
            };
        };
    };
    calibration_status_v1_monitor_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationMonitorResponse"];
                };
            };
        };
    };
    trigger_recalibration_v1_monitor_recalibrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_trigger_recalibration_v1_monitor_recalibrate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecalibrationTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
