"""Synthetic dataset generator with controlled DGP — Module 3.

Objective: demonstrate that the same client has radically different risk
depending on the product and tenor of the operation.

Data Generating Process (DGP) — fully documented and auditable:

PD(client, product, tenor) = sigmoid(
    β_client × financial_score
    + β_tenor × product_effect[product]
    + β_tenor × log(tenor_months)
    + β_interaction × financial_score × log(tenor_months)
    + ε
)

Product effects (β_product):
- capital_de_giro:        0.0  (baseline)
- investimento:          +1.2  (long tenor → structurally higher PD)
- antecipacao_recebiveis: -0.8 (short tenor, embedded collateral → lower PD)

Tenor effect: +0.4 × log(tenor_months)
- 1 month:  log(1) = 0.00 → no additional effect
- 12 months: log(12) = 2.48 → +0.99 in logit
- 48 months: log(48) = 3.87 → +1.55 in logit

Interaction (client × tenor):
- Clients with low score suffer more with longer tenors (β_interaction = -0.3)

Main functions:
- generate_dataset: generates the complete synthetic dataset
- dgp_pd: implements the DGP for PD calculation per contract
"""

import numpy as np
import pandas as pd
from loguru import logger

from src.config import PRODUCTS, TENORS_MONTHS

# ---------------------------------------------------------------------------
# DGP parameters — documented and versioned here
# ---------------------------------------------------------------------------
DGP_PARAMS = {
    "beta_cliente": -2.0,  # high score → lower PD
    "beta_prazo": 0.4,  # longer tenor → higher PD
    "beta_interacao": -0.3,  # low score penalised more at long tenors
    "beta_garantia": -0.6,  # collateral → lower PD
    "product_effects": {
        "capital_de_giro": 0.0,  # baseline
        "investimento": 1.2,  # structural long-tenor risk
        "antecipacao_recebiveis": -0.8,  # embedded collateral (receivables)
    },
    "lgd_base": {
        "capital_de_giro": 0.55,
        "investimento": 0.65,  # no real collateral → higher LGD
        "antecipacao_recebiveis": 0.30,  # receivables as collateral
    },
    "noise_std": 0.5,  # idiosyncratic variability
}


def dgp_pd(
    score_financeiro: np.ndarray,
    produto: str,
    prazo_meses: int,
    has_collateral: np.ndarray,
    params: dict = DGP_PARAMS,
    rng: np.random.Generator | None = None,
) -> np.ndarray:
    """Calculates PD via the controlled DGP.

    Args:
        score_financeiro: Client's normalised score [0,1] (higher = better).
        produto: Product type ('capital_de_giro', 'investimento', 'antecipacao_recebiveis').
        prazo_meses: Tenor in months.
        has_collateral: Binary array (1 = with real collateral).
        params: DGP parameters.
        rng: Numpy random generator.

    Returns:
        Array of PD per contract in [0, 1].
    """
    if rng is None:
        rng = np.random.default_rng(42)

    log_prazo = np.log(max(prazo_meses, 1))

    logit_pd = (
        params["beta_cliente"] * score_financeiro
        + params["beta_prazo"] * log_prazo
        + params["beta_interacao"] * score_financeiro * log_prazo
        + params["product_effects"].get(produto, 0.0)
        + params["beta_garantia"] * has_collateral.astype(float)
        + rng.normal(0, params["noise_std"], size=len(score_financeiro))
    )

    pd_values = 1 / (1 + np.exp(-logit_pd))
    return pd_values


def generate_dataset(
    n: int = 5000,
    seed: int = 42,
) -> pd.DataFrame:
    """Generates synthetic dataset with controlled DGP.

    Each row represents a contract with:
    - Client profile (score_financeiro, age, sector)
    - Operation context (product, tenor, collateral)
    - True PD (generated by DGP) + observed default
    - True LGD (deterministic + noise)
    - EL = PD × LGD × EAD

    The same client appears with multiple products/tenors to
    demonstrate that risk is contextual.

    Args:
        n: Total number of contracts.
        seed: Random seed (reproducible).

    Returns:
        DataFrame with the complete synthetic dataset.
    """
    rng = np.random.default_rng(seed)

    # Number of unique clients (each client has ~3 contracts in different contexts)
    n_clients = n // 3

    # ---------------------------------------------------------------------------
    # Client profiles (fixed per client)
    # ---------------------------------------------------------------------------
    client_ids = np.arange(n_clients)
    score_financeiro = rng.beta(
        a=2, b=3, size=n_clients
    )  # left-skewed distribution
    idade_empresa_anos = rng.integers(1, 30, size=n_clients)
    setor = rng.choice(
        ["comercio", "servicos", "industria", "agronegocio"], size=n_clients
    )
    faturamento_anual = rng.lognormal(mean=12, sigma=1.5, size=n_clients)

    # ---------------------------------------------------------------------------
    # Contracts: cross each client with product × tenor combinations
    # ---------------------------------------------------------------------------
    records = []
    for client_idx in range(n_clients):
        # Draw 3 different contexts for the same client
        contexts = rng.choice(len(PRODUCTS) * len(TENORS_MONTHS), size=3, replace=False)
        for ctx_idx in contexts:
            produto = PRODUCTS[ctx_idx % len(PRODUCTS)]
            prazo = TENORS_MONTHS[ctx_idx // len(PRODUCTS)]

            ead = faturamento_anual[client_idx] * rng.uniform(0.05, 0.40)
            has_collateral = rng.random() < (0.6 if produto == "investimento" else 0.2)

            pd_true = dgp_pd(
                score_financeiro=np.array([score_financeiro[client_idx]]),
                produto=produto,
                prazo_meses=prazo,
                has_collateral=np.array([has_collateral]),
                rng=rng,
            )[0]

            default = int(rng.random() < pd_true)

            lgd_base = DGP_PARAMS["lgd_base"][produto]
            lgd_true = float(np.clip(lgd_base + rng.normal(0, 0.10), 0.01, 0.99))

            el = pd_true * lgd_true * ead

            records.append(
                {
                    "client_id": client_ids[client_idx],
                    "score_financeiro": round(score_financeiro[client_idx], 4),
                    "idade_empresa_anos": int(idade_empresa_anos[client_idx]),
                    "setor": setor[client_idx],
                    "faturamento_anual": round(faturamento_anual[client_idx], 2),
                    "product_type": produto,
                    "tenor_months": prazo,
                    "has_collateral": int(has_collateral),
                    "ead": round(ead, 2),
                    "pd_true": round(pd_true, 6),
                    "lgd_true": round(lgd_true, 4),
                    "el_true": round(el, 2),
                    "default": default,
                }
            )

    df = pd.DataFrame(records).reset_index(drop=True)

    logger.success(
        f"Synthetic dataset generated: {len(df):,} contracts × {df.shape[1]} columns | "
        f"Default rate: {df['default'].mean():.2%} | "
        f"Mean PD: {df['pd_true'].mean():.3f}"
    )
    return df
