"""Contextual model: same client, different products and tenors.

Quantitatively demonstrates why a single score is insufficient:
- Single score: ignores product and tenor
- Contextual score: incorporates product, tenor and interactions

The single score is not wrong — it is insufficient.
In the contextual model, the single score becomes one feature among many.

Main functions:
- train_contextual: trains model with contextual features
- compare_single_vs_contextual: comparative Expected Loss table
- score_by_context: score table per client × product × tenor
"""

import pandas as pd
from lightgbm import LGBMClassifier
from loguru import logger
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from src.config import PRODUCTS, TENORS_MONTHS
from src.contextual.context_features import get_feature_matrix
from src.contextual.data_generator import DGP_PARAMS


def train_contextual(
    df: pd.DataFrame,
    target_col: str = "default",
    test_size: float = 0.2,
    seed: int = 42,
) -> tuple[CalibratedClassifierCV, list[str]]:
    """Trains contextual PD model with LightGBM + Platt scaling.

    Args:
        df: Dataset generated by generate_dataset() with contextual features.
        target_col: Target column (default).
        test_size: Proportion of data for testing.
        seed: Random seed.

    Returns:
        Tuple (calibrated_model, feature_names).
    """
    X, y, feature_names = get_feature_matrix(df, target_col=target_col)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, stratify=y, random_state=seed
    )

    lgbm = LGBMClassifier(
        n_estimators=200,
        learning_rate=0.05,
        num_leaves=31,
        random_state=seed,
        verbose=-1,
    )
    model = CalibratedClassifierCV(lgbm, method="sigmoid", cv=5)
    model.fit(X_train, y_train)

    proba_test = model.predict_proba(X_test)[:, 1]
    auroc = roc_auc_score(y_test, proba_test)
    logger.success(f"Contextual model trained — AUROC: {auroc:.4f}")

    return model, feature_names


def train_single_score(
    df: pd.DataFrame,
    target_col: str = "default",
    seed: int = 42,
) -> CalibratedClassifierCV:
    """Trains baseline model without contextual features (single score).

    Uses only client features, without product/tenor/collateral.

    Args:
        df: Dataset with client features.
        target_col: Target column.
        seed: Random seed.

    Returns:
        Calibrated model (single score).
    """
    # log_tenor only exists after add_context_features() — uses only features
    # present in the raw dataset generated by generate_dataset()
    client_features = ["score_financeiro", "idade_empresa_anos"]
    available = [c for c in client_features if c in df.columns]

    X = df[available].fillna(0)
    y = df[target_col]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=seed
    )

    scaler = StandardScaler()
    lr = LogisticRegression(max_iter=1000, random_state=seed)
    lr.fit(scaler.fit_transform(X_train), y_train)

    proba_test = lr.predict_proba(scaler.transform(X_test))[:, 1]
    auroc = roc_auc_score(y_test, proba_test)
    logger.info(f"Single score baseline — AUROC: {auroc:.4f} (expected to be lower)")

    # Wrapper for uniform interface
    class SingleScoreWrapper:
        def __init__(self, lr, scaler):
            self._lr = lr
            self._scaler = scaler
            self._available = available

        def predict_proba(self, X):
            X_scaled = self._scaler.transform(X[self._available].fillna(0))
            return self._lr.predict_proba(X_scaled)

    return SingleScoreWrapper(lr, scaler)


def score_by_context(
    client_profile: dict,
    model_contextual: CalibratedClassifierCV,
    feature_names: list[str],
    lgd_base: dict = DGP_PARAMS["lgd_base"],
) -> pd.DataFrame:
    """Calculates PD and EL for a client across all contexts (product × tenor).

    Args:
        client_profile: Dictionary with client features.
        model_contextual: Trained contextual model.
        feature_names: List of features used by the model.
        lgd_base: Base LGD per product (from DGP).

    Returns:
        DataFrame with PD, LGD and EL per product × tenor.
    """
    from src.contextual.context_features import (
        add_context_features,
        create_interaction_features,
        encode_product,
    )

    rows = []
    for produto in PRODUCTS:
        for prazo in TENORS_MONTHS:
            row = {**client_profile, "product_type": produto, "tenor_months": prazo}
            rows.append(row)

    df_grid = pd.DataFrame(rows)
    df_grid = add_context_features(df_grid)
    df_grid = encode_product(df_grid, drop_first=True)
    df_grid = create_interaction_features(df_grid)

    # Ensure all features exist
    for col in feature_names:
        if col not in df_grid.columns:
            df_grid[col] = 0

    X = df_grid[feature_names].fillna(0)
    pd_pred = model_contextual.predict_proba(X)[:, 1]

    df_grid["pd_contextual"] = pd_pred
    df_grid["lgd_estimate"] = df_grid["product_type"].map(lgd_base)
    ead = client_profile.get("ead", 100_000)
    df_grid["el_contextual"] = df_grid["pd_contextual"] * df_grid["lgd_estimate"] * ead

    result = df_grid[
        [
            "product_type",
            "tenor_months",
            "pd_contextual",
            "lgd_estimate",
            "el_contextual",
        ]
    ]
    return result.sort_values(["product_type", "tenor_months"])


def compare_single_vs_contextual(
    df: pd.DataFrame,
    n_examples: int = 10,
    seed: int = 42,
) -> pd.DataFrame:
    """Quantitative demonstration: single score vs contextual score.

    Trains both models and compares the computed Expected Loss.
    The central argument: with a single score, the limit/rate decision
    for working capital 30d and investment 48m is the same — which is wrong.

    Args:
        df: Synthetic dataset generated by generate_dataset().
        n_examples: Number of clients to show in the comparison.
        seed: Random seed.

    Returns:
        DataFrame with columns: client_id, product, tenor,
        pd_single, pd_contextual, el_single, el_contextual, el_delta.
    """
    model_ctx, feature_names = train_contextual(df, seed=seed)
    model_single = train_single_score(df, seed=seed)

    from src.contextual.context_features import (
        add_context_features,
        create_interaction_features,
        encode_product,
    )

    df_feat = add_context_features(df.copy())
    df_feat = encode_product(df_feat, drop_first=True)
    df_feat = create_interaction_features(df_feat)

    for col in feature_names:
        if col not in df_feat.columns:
            df_feat[col] = 0

    X_ctx = df_feat[feature_names].fillna(0)
    df_feat["pd_contextual"] = model_ctx.predict_proba(X_ctx)[:, 1]
    df_feat["pd_single"] = model_single.predict_proba(df_feat)[:, 1]

    df_feat["lgd_estimate"] = df_feat["product_type"].map(DGP_PARAMS["lgd_base"])
    df_feat["el_contextual"] = (
        df_feat["pd_contextual"] * df_feat["lgd_estimate"] * df_feat["ead"]
    )
    df_feat["el_single"] = (
        df_feat["pd_single"] * df_feat["lgd_estimate"] * df_feat["ead"]
    )
    df_feat["el_delta"] = df_feat["el_contextual"] - df_feat["el_single"]
    df_feat["el_delta_pct"] = df_feat["el_delta"] / (df_feat["el_single"] + 1) * 100

    sample_clients = (
        df_feat["client_id"].drop_duplicates().sample(n=n_examples, random_state=seed)
    )
    comparison = df_feat[df_feat["client_id"].isin(sample_clients)][
        [
            "client_id",
            "product_type",
            "tenor_months",
            "pd_single",
            "pd_contextual",
            "el_single",
            "el_contextual",
            "el_delta",
            "el_delta_pct",
        ]
    ].sort_values(["client_id", "product_type", "tenor_months"])

    logger.info(
        f"\nMean EL comparison:\n"
        f"  Single score:      {df_feat['el_single'].mean():,.2f}\n"
        f"  Contextual score:  {df_feat['el_contextual'].mean():,.2f}\n"
        f"  Mean delta:        {df_feat['el_delta'].mean():,.2f} ({df_feat['el_delta_pct'].mean():.1f}%)"
    )

    return comparison
